### ISSUE TITLE
ERROR DURING INITIAL SETUP

### ISSUE THREAD

**Issue by paul-100** [mwaaas/ussd_airflow#104]
![image](https://user-images.githubusercontent.com/9849488/27275870-ef45516e-54e1-11e7-9921-345b5fcd384e.png)

**Comment by paul-100** [comment]
plus i am having issue with

` validate_ussd_journey`

**Comment by mwaaas** [comment]
Hey, @paul-100 we currently support only Python 3. Error is because you are using python2

**Comment by paul-100** [comment]
aah okay @mwaaas  thanks that issue has been solved, it will be helpful to be noted that requirements is python 3
