### ISSUE TITLE
Add Currency Formatter.

### ISSUE THREAD

**Issue by eliaskioni** [mwaaas/ussd_airflow#77]
Hi mwas. How can we create a pep like staff for ussd overflow. I mean like a board where someone can request a new feature. Document why the feature should be added and staff like that to make it simple to understand why specific features of overflow were done.

Wanted to request if we can add a currency formatter to allow transformation of numbers like 10000 to 10,000.

**Comment by mwaaas** [comment]
Hmm, think we can still use GitHub issue for feature requests. 

For the currency formatting, would suggest adding it to the built-in filters.

**Comment by mwaaas** [comment]
CLOSED BY #103
